name: wf-cd-release
on:
    push:
        branches:
            - release/**
jobs:
    build-release-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
               ref: "${{github.ref}}"
        - name: Build Website with parcel
          run: npx parcel build "./src/index.html" --dist-dir "./rel-dist" 
        - name:  Upload Build Artifacts
          uses: actions/upload-pages-artifact@v3
          with:
           path: "./rel-dist"
           name: "release-build-artifact" 
    deploy-release-job:
        needs: "build-release-job"
        runs-on: ubuntu-latest
        environment:
             name: "staging-env"
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy Website On GH-Pages
              uses: actions/deploy-pages@v4
              with:
                 artifact_name: "build-artifact-develop"
                 token: "${{github.token}}"
        
           