name: wf-cd-release
on:
    push:
        branches:
            - release/**
jobs:
  build-release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.ref }}"
      - name: Build Website with parcel
        run: npx parcel build "./src/index.html" --dist-dir "./rel-dist"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build-artifact
          path: ./rel-dist

  deploy-release-job:
    needs: build-release-job
    runs-on: ubuntu-latest
    environment:
      name: staging-env
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy Build artifacts in "staging-env"
        uses: actions/deploy-pages@v4
        with:
          artifact_name: release-build-artifact
          token: "${{ github.token }}"
