name:  wf-ci-release
on:
    pull_request:
        branches:
            - release/**
        types:
            - opened
            - synchronize
jobs:
    linting-job-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository From GH Server
              uses: actions/checkout@v4
              with:
                ref: "${{github.ref}}"
            - name: Checkedout branch
              run: echo "${{github.ref}}"
            - name: Lint HTML Files with HTMLHint
              run: npx htmlhint "**/*.html"
            - name: Lint CSS Files with Stylelint
              run: npx stylelint "**/*.css"
            - name: Build Website with Parcel
              run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"